"""
Image-run telemetry. Never invent latency, memory, cost, or quality.

Cold start (backend startup + first load + first image) is distinct from
warm subsequent generation.
"""

from __future__ import annotations

from typing import Any

from newsagent_v2.image.contract import IMAGE_TELEMETRY_SCHEMA_VERSION
from newsagent_v2.image.provider import ProviderResult


def build_image_telemetry(
    *,
    run_id: str,
    event_id: str | None,
    provider_name: str,
    model_name: str | None,
    backend_type: str | None,
    cold_start: bool | None,
    warm_generation: bool | None,
    backend_startup_ms: int | None,
    load_time_ms: int | None,
    generation_time_ms: int | None,
    first_image_latency_ms: int | None,
    total_latency_ms: int | None,
    warm_generation_times_ms: list[int] | None = None,
    peak_memory_mb: float | None = None,
    peak_vram_mb: float | None = None,
    retry_count: int = 0,
    success: bool,
    failure_reason: str | None,
    provider_reported_cost: float | None = None,
    actual_cost_inr: float | None = None,
    timestamp_utc: str,
    sha256: str | None = None,
    width: int | None = None,
    height: int | None = None,
    http_status: int | None = None,
    request_latency_ms: int | None = None,
    cloudflare_request_id: str | None = None,
    response_format: str | None = None,
    size_bytes: int | None = None,
    provider_reported_usage: Any = None,
    provider_reported_neurons: Any = None,
    requested_width: int | None = None,
    requested_height: int | None = None,
    provider_reported_cost_usd: float | None = None,
    provider_reported_image_usage: Any = None,
    provider_reported_tokens: Any = None,
    provider_reported_latency: int | None = None,
    estimated_list_price_usd: float | None = None,
    estimated_list_price_inr: float | None = None,
    estimated_list_price_is_estimate: bool | None = None,
    estimated_list_price_note: str | None = None,
    requested_aspect_ratio: str | None = None,
    requested_resolution_tier: str | None = None,
    provider_request_id: str | None = None,
    total_pipeline_latency_ms: int | None = None,
    reference_used: bool = False,
    reference_role: str | None = None,
    reference_sha256: str | None = None,
    reference_width: int | None = None,
    reference_height: int | None = None,
    provider_reference_supported: bool | None = None,
    reference_required: bool = False,
) -> dict[str, Any]:
    return {
        "schema_version": IMAGE_TELEMETRY_SCHEMA_VERSION,
        "run_id": run_id,
        "event_id": event_id,
        "provider_name": provider_name,
        "model_name": model_name,
        "backend_type": backend_type,
        "cold_start": cold_start,
        "warm_generation": warm_generation,
        "backend_startup_ms": backend_startup_ms,
        "load_time_ms": load_time_ms,
        "generation_time_ms": generation_time_ms,
        "first_image_latency_ms": first_image_latency_ms,
        "total_latency_ms": total_latency_ms,
        "warm_generation_times_ms": list(warm_generation_times_ms or []),
        "peak_memory_mb": peak_memory_mb,
        "peak_vram_mb": peak_vram_mb,
        "retry_count": retry_count,
        "success": success,
        "failure_reason": failure_reason,
        "provider_reported_cost": provider_reported_cost,
        "actual_cost_inr": actual_cost_inr,
        "timestamp_utc": timestamp_utc,
        "sha256": sha256,
        "width": width,
        "height": height,
        "http_status": http_status,
        "request_latency_ms": request_latency_ms,
        "cloudflare_request_id": cloudflare_request_id,
        "response_format": response_format,
        "size_bytes": size_bytes,
        "provider_reported_usage": provider_reported_usage,
        "provider_reported_neurons": provider_reported_neurons,
        "requested_width": requested_width,
        "requested_height": requested_height,
        "provider_reported_cost_usd": provider_reported_cost_usd,
        "provider_reported_image_usage": provider_reported_image_usage,
        "provider_reported_tokens": provider_reported_tokens,
        "provider_reported_latency": provider_reported_latency,
        "estimated_list_price_usd": estimated_list_price_usd,
        "estimated_list_price_inr": estimated_list_price_inr,
        "estimated_list_price_is_estimate": estimated_list_price_is_estimate,
        "estimated_list_price_note": estimated_list_price_note,
        "requested_aspect_ratio": requested_aspect_ratio,
        "requested_resolution_tier": requested_resolution_tier,
        "provider_request_id": provider_request_id,
        "total_pipeline_latency_ms": total_pipeline_latency_ms,
        "reference_used": reference_used,
        "reference_role": reference_role,
        "reference_sha256": reference_sha256,
        "reference_width": reference_width,
        "reference_height": reference_height,
        "provider_reference_supported": provider_reference_supported,
        "reference_required": reference_required,
        "quality_score": None,
        "invented_metrics": False,
    }


def telemetry_from_result(
    *,
    run_id: str,
    event_id: str | None,
    result: ProviderResult,
    timestamp_utc: str,
    warm_generation_times_ms: list[int] | None = None,
    reference: dict[str, Any] | None = None,
) -> dict[str, Any]:
    ref = reference or {}
    return build_image_telemetry(
        run_id=run_id,
        event_id=event_id,
        provider_name=result.provider_name,
        model_name=result.model_name,
        backend_type=result.backend_type,
        cold_start=result.cold_start,
        warm_generation=result.warm_generation,
        backend_startup_ms=result.backend_startup_ms,
        load_time_ms=result.load_time_ms,
        generation_time_ms=result.generation_time_ms,
        first_image_latency_ms=result.first_image_latency_ms,
        total_latency_ms=result.total_latency_ms,
        warm_generation_times_ms=warm_generation_times_ms,
        peak_memory_mb=result.peak_memory_mb,
        peak_vram_mb=result.peak_vram_mb,
        retry_count=result.retry_count,
        success=result.success,
        failure_reason=result.failure_reason,
        provider_reported_cost=result.provider_reported_cost,
        actual_cost_inr=result.actual_cost_inr,
        timestamp_utc=timestamp_utc,
        sha256=result.sha256,
        width=result.width,
        height=result.height,
        http_status=result.http_status,
        request_latency_ms=result.request_latency_ms,
        cloudflare_request_id=result.cloudflare_request_id,
        response_format=result.response_format,
        size_bytes=result.size_bytes,
        provider_reported_usage=result.provider_reported_usage,
        provider_reported_neurons=result.provider_reported_neurons,
        requested_width=result.requested_width,
        requested_height=result.requested_height,
        provider_reported_cost_usd=result.provider_reported_cost_usd,
        provider_reported_image_usage=result.provider_reported_image_usage,
        provider_reported_tokens=result.provider_reported_tokens,
        provider_reported_latency=result.provider_reported_latency,
        estimated_list_price_usd=result.estimated_list_price_usd,
        estimated_list_price_inr=result.estimated_list_price_inr,
        estimated_list_price_is_estimate=result.estimated_list_price_is_estimate,
        estimated_list_price_note=result.estimated_list_price_note,
        requested_aspect_ratio=result.requested_aspect_ratio,
        requested_resolution_tier=result.requested_resolution_tier,
        provider_request_id=result.provider_request_id,
        total_pipeline_latency_ms=result.total_pipeline_latency_ms,
        reference_used=bool(ref.get("reference_used")),
        reference_role=ref.get("reference_role"),
        reference_sha256=ref.get("reference_sha256"),
        reference_width=ref.get("reference_width"),
        reference_height=ref.get("reference_height"),
        provider_reference_supported=ref.get("provider_reference_supported"),
        reference_required=bool(ref.get("reference_required")),
    )
